In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.style as style
from sklearn.feature_extraction import text
import warnings
pd.reset_option('display.max_colwidth')

In [57]:
# veriyi okuyoruz
df=pd.read_csv('dataset.csv')
df.head()

url  \
0  https://www.ted.com/talks/niro_sivanathan_the_...   
1  https://www.ted.com/talks/yen_pham_why_should_...   
2  https://www.ted.com/talks/tilak_mandadi_3_ways...   
3  https://www.ted.com/talks/a_j_jacobs_the_life_...   
4  https://www.ted.com/talks/tom_schuler_how_we_c...   

                                             title  \
0   The counterintuitive way to be more persuasive   
1   Why should you read Toni Morrison's "Beloved"?   
2  3 ways companies can support grieving employees   
3                The life cycle of a cup of coffee   
4       How we could make carbon-negative concrete   

                                                tags  \
0  ['TED', 'talks', 'communication', 'mind', 'psy...   
1  ['TED', 'talks', 'TED-Ed', 'animation', 'educa...   
2  ['TED', 'talks', 'empathy', 'work', 'culture',...   
3  ['TED', 'talks', 'education', 'TED-Ed', 'agric...   
4  ['TED', 'talks', 'climate change', 'Countdown'...   

                                             details  
0  What's the best way to make a good point? Orga...  
1  Two tiny handprints stamped into a cake. A mir...  
2  When we experience loss, grief travels with us...  
3  How many people does it take to make a cup of ...  
4  Concrete is all around us: we use it to build ...

In [58]:
df.columns

Index(['url', 'title', 'tags', 'details'], dtype='object')

In [59]:
df.describe()

url  \
count                                                4921   
unique                                               4921   
top     https://www.ted.com/talks/gabby_rivera_the_sto...   
freq                                                    1   

                                  title                                tags  \
count                              4921                                4921   
unique                             4921                                4877   
top     What our language habits reveal  ['TED', 'talks', 'TED-Ed', 'math']   
freq                                  1                                   8   

                                                  details  
count                                                4921  
unique                                               4920  
top     How do we make sense of a world that doesn't? ...  
freq                                                    2

In [60]:
df.isnull().sum()

url        0
title      0
tags       0
details    0
dtype: int64

In [61]:
df_txt=df[['url', 'title','details', 'tags']]
df_txt

url  \
0     https://www.ted.com/talks/niro_sivanathan_the_...   
1     https://www.ted.com/talks/yen_pham_why_should_...   
2     https://www.ted.com/talks/tilak_mandadi_3_ways...   
3     https://www.ted.com/talks/a_j_jacobs_the_life_...   
4     https://www.ted.com/talks/tom_schuler_how_we_c...   
...                                                 ...   
4916  https://www.ted.com/talks/hans_rosling_the_bes...   
4917  https://www.ted.com/talks/sir_ken_robinson_do_...   
4918  https://www.ted.com/talks/majora_carter_greeni...   
4919  https://www.ted.com/talks/david_pogue_simplici...   
4920  https://www.ted.com/talks/al_gore_averting_the...   

                                                title  \
0      The counterintuitive way to be more persuasive   
1      Why should you read Toni Morrison's "Beloved"?   
2     3 ways companies can support grieving employees   
3                   The life cycle of a cup of coffee   
4          How we could make carbon-negative concrete   
...                                               ...   
4916                  The best stats you've ever seen   
4917                      Do schools kill creativity?   
4918                              Greening the ghetto   
4919                                 Simplicity sells   
4920                      Averting the climate crisis   

                                                details  \
0     What's the best way to make a good point? Orga...   
1     Two tiny handprints stamped into a cake. A mir...   
2     When we experience loss, grief travels with us...   
3     How many people does it take to make a cup of ...   
4     Concrete is all around us: we use it to build ...   
...                                                 ...   
4916  You've never seen data presented like this. Wi...   
4917  Sir Ken Robinson makes an entertaining and pro...   
4918  In an emotionally charged talk, MacArthur-winn...   
4919  New York Times columnist David Pogue takes aim...   
4920  With the same humor and humanity he exuded in ...   

                                                   tags  
0     ['TED', 'talks', 'communication', 'mind', 'psy...  
1     ['TED', 'talks', 'TED-Ed', 'animation', 'educa...  
2     ['TED', 'talks', 'empathy', 'work', 'culture',...  
3     ['TED', 'talks', 'education', 'TED-Ed', 'agric...  
4     ['TED', 'talks', 'climate change', 'Countdown'...  
...                                                 ...  
4916  ['TED', 'talks', 'Africa', 'Asia', 'Google', '...  
4917  ['TED', 'talks', 'children', 'creativity', 'cu...  
4918  ['TED', 'talks', 'MacArthur grant', 'activism'...  
4919  ['TED', 'talks', 'computers', 'entertainment',...  
4920  ['TED', 'talks', 'alternative energy', 'cars',...  

[4921 rows x 4 columns]

In [62]:
import re
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
def remove_tags(string):
    #re.sub for replacement(html ifadeleri geldiyse silmeliyiz)
    result = re.sub('<.*?>','',string)
    return result

In [64]:
#details verilerindeki html ifadelerini silmek için
df_txt['details'] = df_txt['details'].apply(lambda cw : remove_tags(cw))

In [65]:
#hepsii küçük harf yapıyoruz.
df_txt['details']=df['details'].str.lower()
df_txt['title']=df['title'].str.lower()

In [66]:
df_txt

url  \
0     https://www.ted.com/talks/niro_sivanathan_the_...   
1     https://www.ted.com/talks/yen_pham_why_should_...   
2     https://www.ted.com/talks/tilak_mandadi_3_ways...   
3     https://www.ted.com/talks/a_j_jacobs_the_life_...   
4     https://www.ted.com/talks/tom_schuler_how_we_c...   
...                                                 ...   
4916  https://www.ted.com/talks/hans_rosling_the_bes...   
4917  https://www.ted.com/talks/sir_ken_robinson_do_...   
4918  https://www.ted.com/talks/majora_carter_greeni...   
4919  https://www.ted.com/talks/david_pogue_simplici...   
4920  https://www.ted.com/talks/al_gore_averting_the...   

                                                title  \
0      the counterintuitive way to be more persuasive   
1      why should you read toni morrison's "beloved"?   
2     3 ways companies can support grieving employees   
3                   the life cycle of a cup of coffee   
4          how we could make carbon-negative concrete   
...                                               ...   
4916                  the best stats you've ever seen   
4917                      do schools kill creativity?   
4918                              greening the ghetto   
4919                                 simplicity sells   
4920                      averting the climate crisis   

                                                details  \
0     what's the best way to make a good point? orga...   
1     two tiny handprints stamped into a cake. a mir...   
2     when we experience loss, grief travels with us...   
3     how many people does it take to make a cup of ...   
4     concrete is all around us: we use it to build ...   
...                                                 ...   
4916  you've never seen data presented like this. wi...   
4917  sir ken robinson makes an entertaining and pro...   
4918  in an emotionally charged talk, macarthur-winn...   
4919  new york times columnist david pogue takes aim...   
4920  with the same humor and humanity he exuded in ...   

                                                   tags  
0     ['TED', 'talks', 'communication', 'mind', 'psy...  
1     ['TED', 'talks', 'TED-Ed', 'animation', 'educa...  
2     ['TED', 'talks', 'empathy', 'work', 'culture',...  
3     ['TED', 'talks', 'education', 'TED-Ed', 'agric...  
4     ['TED', 'talks', 'climate change', 'Countdown'...  
...                                                 ...  
4916  ['TED', 'talks', 'Africa', 'Asia', 'Google', '...  
4917  ['TED', 'talks', 'children', 'creativity', 'cu...  
4918  ['TED', 'talks', 'MacArthur grant', 'activism'...  
4919  ['TED', 'talks', 'computers', 'entertainment',...  
4920  ['TED', 'talks', 'alternative energy', 'cars',...  

[4921 rows x 4 columns]

In [67]:
desc_text = df_txt['details'].tolist()
tfidf = text.TfidfVectorizer(input = desc_text, stop_words = "english")
desc_matrix = tfidf.fit_transform(desc_text)
print(desc_matrix.shape)

(4921, 24038)


In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
cosine_sim_desc = cosine_similarity(desc_matrix)
print(cosine_sim_desc)

[[1.         0.         0.01914579 ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.02642128 0.         0.        ]
 [0.01914579 0.         1.         ... 0.00541727 0.         0.01637537]
 ...
 [0.         0.02642128 0.00541727 ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.01082616]
 [0.         0.         0.01637537 ... 0.         0.01082616 1.        ]]


In [85]:
indices = pd.Series(df.index, index = df['title'])
def talk_recommend(url):

    idx = indices[url]
    sim_scores = list(enumerate(cosine_sim_desc[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:31]

    talk_indices = [i[0] for i in sim_scores]

    return df_txt.iloc[talk_indices]

In [71]:
#tagleri düzenlemek
import re

In [72]:
def clean_text(x):
    letter_only = re.sub("[^a-zA-Z]", " ", x)
    return ' '.join(letter_only.split()).lower()

In [73]:
df_txt.tags = df_txt.tags.astype('str')

In [74]:
df_txt['tags'] = df_txt['tags'].apply(clean_text)

In [75]:
df_txt.head()

url  \
0  https://www.ted.com/talks/niro_sivanathan_the_...   
1  https://www.ted.com/talks/yen_pham_why_should_...   
2  https://www.ted.com/talks/tilak_mandadi_3_ways...   
3  https://www.ted.com/talks/a_j_jacobs_the_life_...   
4  https://www.ted.com/talks/tom_schuler_how_we_c...   

                                             title  \
0   the counterintuitive way to be more persuasive   
1   why should you read toni morrison's "beloved"?   
2  3 ways companies can support grieving employees   
3                the life cycle of a cup of coffee   
4       how we could make carbon-negative concrete   

                                             details  \
0  what's the best way to make a good point? orga...   
1  two tiny handprints stamped into a cake. a mir...   
2  when we experience loss, grief travels with us...   
3  how many people does it take to make a cup of ...   
4  concrete is all around us: we use it to build ...   

                                                tags  
0  ted talks communication mind psychology cognit...  
1  ted talks ted ed animation education literatur...  
2  ted talks empathy work culture death communica...  
3  ted talks education ted ed agriculture food an...  
4  ted talks climate change countdown innovation ...

In [76]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
cv_tags = cv.fit_transform(df_txt['tags'])
#df_genres = pd.DataFrame(cv_tags.todense(), columns = cv.get_feature_names(), index = df_txt['title'])

In [77]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = cosine_similarity(cv_tags)

In [78]:
def get_recommendation_based_tags(x):
    index_to_search = df[df['title'] == x].index[0]
    series_similar = pd.Series(cos_sim[index_to_search])
    index_similar = series_similar.sort_values(ascending = False).head(10).index
    return df_txt.loc[index_similar]

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')

matrix = tf.fit_transform(df_txt['title'])

In [80]:
from sklearn.metrics.pairwise import linear_kernel

cosine_similarities_title = linear_kernel(matrix, matrix)
print(cosine_similarities_title)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [81]:
indices = pd.Series(df.index, index = df['title'])
#print(indices)
def talk_recommend_title(title):

    idx = indices[title]
    sim_scores = list(enumerate(cosine_similarities_title[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:31]

    talk_indices = [i[0] for i in sim_scores]

    return df_txt.iloc[talk_indices]

In [94]:
pd.set_option('display.max_colwidth', None)
print("Similars based title : \n")
talk_recommend_title('Do schools kill creativity?').head(10)

Similars based title : 



url  \
3527                 https://www.ted.com/talks/julie_burstein_4_lessons_in_creativity   
3354   https://www.ted.com/talks/geoffrey_canada_our_failing_schools_enough_is_enough   
4583                   https://www.ted.com/talks/isaac_mizrahi_fashion_and_creativity   
3143               https://www.ted.com/talks/suzanne_talhouk_don_t_kill_your_language   
2732                   https://www.ted.com/talks/bel_pesce_5_ways_to_kill_your_dreams   
3335              https://www.ted.com/talks/ron_shaneyfelt_is_space_trying_to_kill_us   
1716  https://www.ted.com/talks/linda_zhang_why_schools_should_teach_entrepreneurship   
4590                 https://www.ted.com/talks/tim_brown_tales_of_creativity_and_play   
4702                     https://www.ted.com/talks/amy_tan_where_does_creativity_hide   
3126             https://www.ted.com/talks/alan_iny_reigniting_creativity_in_business   

                                          title  \
3527                    4 lessons in creativity   
3354     our failing schools. enough is enough!   
4583                     fashion and creativity   
3143                   don't kill your language   
2732                 5 ways to kill your dreams   
3335                is space trying to kill us?   
1716  why schools should teach entrepreneurship   
4590               tales of creativity and play   
4702                where does creativity hide?   
3126          reigniting creativity in business   

                                                                                                                                                                                                                                                                                                                                                                                                              details  \
3527                                                                                                                            radio host julie burstein talks with creative people for a living -- and shares four lessons about how to create in the face of challenge, self-doubt and loss. hear insights from filmmaker mira nair, writer richard ford, sculptor richard serra and photographer joel meyerowitz.   
3354  why, why, why does our education system look so similar to the way it did 50 years ago? millions of students were failing then, as they are now -- and it’s because we’re clinging to a business model that clearly doesn’t work. education advocate geoffrey canada dares the system to look at the data, think about the customers and make systematic shifts in order to help greater numbers of kids excel.   
4583                                                                                                                                                  fashion designer isaac mizrahi spins through a dizzying array of inspirations -- from '50s pinups to a fleeting glimpse of a woman on the street who makes him shout "stop the cab!" inside this rambling talk are real clues to living a happy, creative life.   
3143                                                                                   more and more, english is a global language; speaking it is perceived as a sign of being modern. but -- what do we lose when we leave behind our mother tongues? suzanne talhouk makes an impassioned case to love your own language, and to cherish what it can express that no other language can. in arabic with subtitles.   
2732                                                                                                      all of us want to invent that game-changing product, launch that successful company, write that best-selling book. and yet so few of us actually do it. ted fellow and brazilian entrepreneur bel pesce breaks down five easy-to-believe myths that ensure your dream projects will never come to fruition.   
3335                                                               how likely is it th

In [95]:
print("Similars based tags : \n")
get_recommendation_based_tags('Do schools kill creativity?')['url']

Similars based tags : 



4917                               https://www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity
1046         https://www.ted.com/talks/olympia_della_flora_creative_ways_to_get_kids_to_thrive_in_school
3469                                          https://www.ted.com/talks/colin_powell_kids_need_structure
1207    https://www.ted.com/talks/the_ted_interview_sir_ken_robinson_still_wants_an_education_revolution
3356           https://www.ted.com/talks/pearl_arredondo_my_story_from_gangland_daughter_to_star_teacher
3364                                   https://www.ted.com/talks/rita_pierson_every_kid_needs_a_champion
3352                   https://www.ted.com/talks/sir_ken_robinson_how_to_escape_education_s_death_valley
4230                         https://www.ted.com/talks/sir_ken_robinson_bring_on_the_learning_revolution
4268                              https://www.ted.com/talks/adora_svitak_what_adults_can_learn_from_kids
4092                               https://www.ted.com/

In [96]:
print("Similars based details : \n")
print(talk_recommend('Do schools kill creativity?').head(10)['url'])

Similars based details : 

1207    https://www.ted.com/talks/the_ted_interview_sir_ken_robinson_still_wants_an_education_revolution
4230                         https://www.ted.com/talks/sir_ken_robinson_bring_on_the_learning_revolution
3352                   https://www.ted.com/talks/sir_ken_robinson_how_to_escape_education_s_death_valley
4089                             https://www.ted.com/talks/sir_ken_robinson_changing_education_paradigms
3279                                        https://www.ted.com/talks/tom_thum_the_orchestra_in_my_mouth
2445           https://www.ted.com/talks/laura_robinson_the_secrets_i_find_on_the_mysterious_ocean_floor
3845                                        https://www.ted.com/talks/kathryn_schulz_don_t_regret_regret
4849                                     https://www.ted.com/talks/chris_bangle_great_cars_are_great_art
4211                       https://www.ted.com/talks/cameron_herold_let_s_raise_kids_to_be_entrepreneurs
813                         

In [97]:
indices = pd.Series(df.index, index = df['title'])
def talk_recommend_forall(title, tags_rate, title_rate, details_rate):

    idx = indices[title]
    sim_scores_title = list(enumerate(cosine_similarities_title[idx]))
    sim_scores_tags = list(enumerate(cos_sim[idx]))
    sim_scores_desc = list(enumerate(cosine_sim_desc[idx]))
    result = [[0 for x in range(2)] for y in range(df_txt.shape[0])]
    for i in range(0, df_txt.shape[0]):
        result[i][0] = i
        result[i][1] = title_rate * sim_scores_title[i][1] + sim_scores_tags[i][1] * tags_rate + sim_scores_desc[i][1] * details_rate
#oranlar degiskene atılsın, kullanıcı versin
    result = sorted(result, key=lambda x: x[1], reverse=True)

    result = result[1:31]

    talk_indices = [i[0] for i in result]

    return df_txt.iloc[talk_indices]

In [98]:
talk_recommend_forall('Do schools kill creativity?', 0.5, 0.1, 0.4).head(10)

url  \
1207  https://www.ted.com/talks/the_ted_interview_sir_ken_robinson_still_wants_an_education_revolution   
4230                       https://www.ted.com/talks/sir_ken_robinson_bring_on_the_learning_revolution   
3352                 https://www.ted.com/talks/sir_ken_robinson_how_to_escape_education_s_death_valley   
1046       https://www.ted.com/talks/olympia_della_flora_creative_ways_to_get_kids_to_thrive_in_school   
3469                                        https://www.ted.com/talks/colin_powell_kids_need_structure   
3356         https://www.ted.com/talks/pearl_arredondo_my_story_from_gangland_daughter_to_star_teacher   
4268                            https://www.ted.com/talks/adora_svitak_what_adults_can_learn_from_kids   
847        https://www.ted.com/talks/claudia_miner_a_new_way_to_get_every_child_ready_for_kindergarten   
3354                    https://www.ted.com/talks/geoffrey_canada_our_failing_schools_enough_is_enough   
3364                                 https://www.ted.com/talks/rita_pierson_every_kid_needs_a_champion   

                                                       title  \
1207  sir ken robinson (still) wants an education revolution   
4230                       bring on the learning revolution!   
3352                  how to escape education's death valley   
1046           creative ways to get kids to thrive in school   
3469                                     kids need structure   
3356        my story, from gangland daughter to star teacher   
4268                         what adults can learn from kids   
847      a new way to get every child ready for kindergarten   
3354                  our failing schools. enough is enough!   
3364                              every kid needs a champion   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      details  \
1207                                                                                do schools kill creativity? back in 2006, sir ken robinson posed this question to the ted audience -- and boy, did it touch a nerve. more than fifty million views and a decade later, head of ted chris anderson sits down with sir ken to dig into the changes and progress that have been made, and to see if the answer now is any different. how are educators thinking about creativity these days? and why should creativity be a focus at all? with his characteristic verve, wit and sparkle, sir ken explains all. (audio only)   
4230                                                                                                                                                                                                                                                                                                                                                                                       in this poignant, funny follow-up to his fabled 2006 talk, sir ken robinson makes the case for a radical shift from standardized schools to personalized learning -- creating conditions where kids' natural talents can flourish.   
3352                                                                                                                                                                                                                                                                                                    sir ken robinson outlines 3 principles crucial for the human mind to flourish -- and how current educati

In [99]:
def printMenu():

    print("\n\n<Welcome to TED Talks Recommendation Project>\n")
    print("Opeations :\n")
    print("1 - Recommendation based title.\n")
    print("2 - Recommendation based tags.\n")
    print("3 - Recommendation based details.\n")
    print("4 - Recommendation based all.\n")
    print("0 - Quit.\n")

In [102]:
def rec():
    select = 1
    while(int(select)):
        printMenu()
        select = input("Please select an operation\n\t> ")
        if(int(select) == 1):# title
            title = input("Enter a title:")
            print(talk_recommend_title(title)['url'].head(10))
        elif(int(select) == 2):# tags
            title = input("Enter a title: ")
            print(get_recommendation_based_tags(title)['url'])
        elif(int(select) == 3):# details
            title = input("Enter a title: ")
            print(talk_recommend(title)['url'].head(10))
        elif(int(select) == 4):# all
            tags_rate = input("Please enter the similarity rate of tags: ")
            title_rate = input("Please enter the similarity rate of title: ")
            details_rate = input("Please enter the similarity rate of details: ")
            title = input("Enter a title: ")
            print(talk_recommend_forall(title, float(tags_rate), float(title_rate), float(details_rate)).head(10)['url'])
        elif(int(select) == 0):
            select = 0
        else:
            print("Please enter a valid operation.\n")

In [103]:
rec()



<Welcome to TED Talks Recommendation Project>

Opeations :

1 - Recommendation based title.

2 - Recommendation based tags.

3 - Recommendation based details.

4 - Recommendation based all.

0 - Quit.

Please select an operation
	> 1
Enter a title:Do schools kill creativity?
3527                   https://www.ted.com/talks/julie_burstein_4_lessons_in_creativity
3354     https://www.ted.com/talks/geoffrey_canada_our_failing_schools_enough_is_enough
4583                     https://www.ted.com/talks/isaac_mizrahi_fashion_and_creativity
3143                 https://www.ted.com/talks/suzanne_talhouk_don_t_kill_your_language
2732                     https://www.ted.com/talks/bel_pesce_5_ways_to_kill_your_dreams
3335                https://www.ted.com/talks/ron_shaneyfelt_is_space_trying_to_kill_us
1716    https://www.ted.com/talks/linda_zhang_why_schools_should_teach_entrepreneurship
4590                   https://www.ted.com/talks/tim_brown_tales_of_creativity_and_play
4702              